version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springdockerdev
    ports:
      - "8080:8080"
    develop:
      watch:
        # Sync source files directly into the container (instant updates)
        - action: sync+restart
          path: ./src
          target: /app/src
        # If POM changes, rebuild the whole image
        - action: rebuild
          path: pom.xml
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgresdb
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: